#dvdrental postgresql connection
spring.datasource.url=jdbc:postgresql://localhost:5432/student_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


#java camelCase - JSON snake_case(filmId -> film_id)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.main.allow-bean-definition-overriding=true
server.port =8080
debug=true